services:
  updater:
    build: .
    volumes:
      - .:/usr/src/app
    # This command will run the script, wait an hour (3600s), and then repeat.
    command: >
      sh -c "while true; do python app.py; sleep 3600; done"

  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    depends_on:
      - updater
